# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-10-23 05:52
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('client', '0002_auto_20171020_0231'),
    ]

    operations = [
        migrations.CreateModel(
            name='WaitList',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(help_text='Titre', max_length=100)),
                ('img', models.CharField(help_text='Image de la chanson', max_length=100)),
                ('ytid', models.CharField(help_text='Youtube Id.', max_length=30)),
                ('duration', models.CharField(help_text='Durée de la chanson', max_length=10)),
                ('time', models.DateTimeField(auto_now_add=True)),
                ('requestid', models.UUIDField(help_text='Unique request ID')),
            ],
        ),
        migrations.AddField(
            model_name='song',
            name='duration',
            field=models.CharField(default='', help_text='Durée de la chanson', max_length=10),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='song',
            name='img',
            field=models.CharField(default='', help_text='Image de la chanson', max_length=100),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='song',
            name='ytid',
            field=models.CharField(help_text='Youtube Id.', max_length=30),
        ),
    ]
