# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-10-23 06:00
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('client', '0003_auto_20171023_0152'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='waitlist',
            options={'ordering': ['time']},
        ),
    ]
