# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-10-23 06:23
from __future__ import unicode_literals

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('client', '0004_auto_20171023_0200'),
    ]

    operations = [
        migrations.AlterField(
            model_name='waitlist',
            name='requestid',
            field=models.UUIDField(default=uuid.uuid4, help_text='Unique request ID'),
        ),
    ]
