# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-10-24 04:11
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('client', '0005_auto_20171023_0223'),
    ]

    operations = [
        migrations.AlterField(
            model_name='group',
            name='name',
            field=models.CharField(help_text='Entrez un nom de groupe.', max_length=50),
        ),
        migrations.AlterField(
            model_name='song',
            name='artist',
            field=models.ManyToManyField(blank=True, help_text='Choisissez les artistes.', to='client.Artist'),
        ),
        migrations.AlterField(
            model_name='song',
            name='group',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='client.Group'),
        ),
    ]
