# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-10-24 04:23
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('client', '0006_auto_20171024_0011'),
    ]

    operations = [
        migrations.AlterField(
            model_name='song',
            name='genre',
            field=models.ManyToManyField(blank=True, help_text='Choisissez un genre musical.', to='client.Genre'),
        ),
    ]
