# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-10-24 04:37
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('client', '0007_auto_20171024_0023'),
    ]

    operations = [
        migrations.AlterField(
            model_name='song',
            name='language',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='client.Language'),
        ),
    ]
