# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-10-24 04:44
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('client', '0008_auto_20171024_0037'),
    ]

    operations = [
        migrations.AlterField(
            model_name='group',
            name='members',
            field=models.ManyToManyField(blank='True', help_text='Choisissez les membres du groupe.', to='client.Artist'),
        ),
    ]
