# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-10-26 22:58
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('client', '0009_auto_20171024_0044'),
    ]

    operations = [
        migrations.CreateModel(
            name='Actions',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('time', models.DateTimeField(auto_now_add=True)),
                ('name', models.CharField(help_text='Titre', max_length=10)),
            ],
            options={
                'ordering': ['time'],
            },
        ),
    ]
