# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2018-01-05 02:48
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('client', '0010_actions'),
    ]

    operations = [
        migrations.AlterField(
            model_name='song',
            name='duration',
            field=models.CharField(help_text='Durée de la chanson', max_length=20),
        ),
        migrations.AlterField(
            model_name='waitlist',
            name='duration',
            field=models.CharField(help_text='Durée de la chanson', max_length=20),
        ),
    ]
